# Project-wide Gradle settings.

# JVM memory - disesuaikan untuk RAM 8GB
# Xmx1536m lebih aman agar tidak crash karena RAM habis
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseG1GC

# Gradle daemon
org.gradle.daemon=true

# Build paralel
org.gradle.parallel=true

org.gradle.configureondemand=false

# AndroidX
android.useAndroidX=true

# Nonaktifkan R8 full mode
android.enableR8.fullMode=false